#!/bin/dash
sudo apt-get -qq update  ;
	sudo apt-get dist-upgrade --assume-no > ~/hophop;
	updates=$(grep ^0\  ~/hophop| wc -l);
		if [ $updates = 1 ]; 
		then 
		echo "Geen updates beschikbaar op `hostname`.";
		rm ~/hophop;
		echo  "Lastrun op `hostname` "$(date);
		exit 0;
		else 
		sudo apt-get dist-upgrade -y;
		sudo apt-get clean;
			autoremove=$(grep autoremove ~/hophop|wc -l);
			if [ $autoremove = 1 ];
			then sudo apt-get autoremove -y;
			fi;
		fi;
	rm ~/hophop;
	echo  "Lastrun op `hostname`" $(date);
